// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgF1ajIXmQkk-Ysg38kdKWKj6MgoQODmk',
    appId: '1:612618064022:web:ff795f0914b833c9ee32b7',
    messagingSenderId: '612618064022',
    projectId: 'gestionmaestrosplitter',
    authDomain: 'gestionmaestrosplitter.firebaseapp.com',
    storageBucket: 'gestionmaestrosplitter.appspot.com',
    measurementId: 'G-ZHDXBBF3XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVelIXBMn_tJL08Y4KRhIMsYz5hM4uc3g',
    appId: '1:612618064022:android:688df94b47654fe7ee32b7',
    messagingSenderId: '612618064022',
    projectId: 'gestionmaestrosplitter',
    storageBucket: 'gestionmaestrosplitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7nsI_m_XJ89fNKwoQ4bnRubhoEF2Fc2Y',
    appId: '1:612618064022:ios:65b3528e336903d8ee32b7',
    messagingSenderId: '612618064022',
    projectId: 'gestionmaestrosplitter',
    storageBucket: 'gestionmaestrosplitter.appspot.com',
    iosBundleId: 'com.example.split',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7nsI_m_XJ89fNKwoQ4bnRubhoEF2Fc2Y',
    appId: '1:612618064022:ios:65b3528e336903d8ee32b7',
    messagingSenderId: '612618064022',
    projectId: 'gestionmaestrosplitter',
    storageBucket: 'gestionmaestrosplitter.appspot.com',
    iosBundleId: 'com.example.split',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgF1ajIXmQkk-Ysg38kdKWKj6MgoQODmk',
    appId: '1:612618064022:web:869e712180faf201ee32b7',
    messagingSenderId: '612618064022',
    projectId: 'gestionmaestrosplitter',
    authDomain: 'gestionmaestrosplitter.firebaseapp.com',
    storageBucket: 'gestionmaestrosplitter.appspot.com',
    measurementId: 'G-WKQ699E44C',
  );
}
